# Usage:
#   $ docker-compose -f docker-compose-dev-env.yml up -d
#   $ docker-compose -f docker-compose-dev-env.yml down
version: '3.8'

services:
  project-dev-env:
    build:
      context: .
      dockerfile: dockerfile-dev-env
      args:
        DEFAULT_USER: ${DEFAULT_USER:-dev}
        WORKDIR: /home/${DEFAULT_USER:-dev}/workdir
    volumes:
      - ../../:/home/${DEFAULT_USER:-dev}/workdir/${COMPOSE_PROJECT_NAME:-project}
    tty: true
    stdin_open: true
  