# Usage:
#   $ docker-compose -f docker-compose.dev-env.yml up -d
#   $ docker-compose -f docker-compose.dev-env.yml down
version: '3.8'

services:
  project-dev-env:
    build:
      # Note:
      #   由於 configure-bashrc.sh 與 Dockerfile 不在同一目錄下, 所以 docker image build 時必須指定 build context 
      #   為 .dev-env 目錄, 並且指定 dockerfile 為 docker/Dockerfile.dev-env
      context: ../
      dockerfile: docker/Dockerfile.dev-env
      args:
        DEFAULT_USER: ${DEFAULT_USER:-dev}
        WORKDIR: /home/${DEFAULT_USER:-dev}/workdir/${COMPOSE_PROJECT_NAME:-project}
    volumes:
      - ../../:/home/${DEFAULT_USER:-dev}/workdir/${COMPOSE_PROJECT_NAME:-project}
    # command: ["bash"]  # Optional, 因為 Dockerfile 中已經設定了 CMD ["bash"]
    # tty 與 stdin_open 設定為 true, 以支持 docker exec -it <container_id> 交互式操作
    tty: true
    stdin_open: true
  