name: CI (lint, test, build)

on:
  push:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  ci:
    name: Continuous Integration (CI)
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies (npm-install)
        run: npm ci

      - name: Run Linter (npm-lint)
        run: npm run lint

      - name: Run Tests (unit-test)
        run: npm run test:coverage

      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow#example
      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Archive Code Coverage Report (Only for Node.js 22)
        uses: actions/upload-artifact@v4
        if: ${{ matrix.node-version == 22 }}
        with:
          name: code-coverage-report
          path: coverage/

      - name: Build the App with No Emit (build-app)
        run: npm run build:noEmit

  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-22.04
    needs: ci
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow#downloading-artifacts-during-a-workflow-run
      # https://github.com/marketplace/actions/download-a-build-artifact
      - name: Download Code Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
